<a href="https://colab.research.google.com/github/2303A51641/1641_batach-29_PDS/blob/main/lab3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

2D_array

In [3]:
import numpy as np

test_scores = np.random.randint(0, 101, size=(4, 4))
print(test_scores)

column_means = np.mean(test_scores, axis=0)
row_means = np.mean(test_scores, axis=1)

print("Column-wise means:", column_means)
print("Row-wise means:", row_means)

std_dev = np.std(test_scores)
variance = np.var(test_scores)

print("Standard Deviation:", std_dev)
print("Variance:", variance)

min_value = np.min(test_scores)
max_value = np.max(test_scores)
min_index = np.argmin(test_scores)
max_index = np.argmax(test_scores)

print("Minimum value:", min_value)
print("Maximum value:", max_value)
print("Index of minimum value:", min_index)
print("Index of maximum value:", max_index)

[[34 51  8  9]
 [68 81  6 42]
 [88 19 54 49]
 [45 83 12 75]]
Column-wise means: [58.75 58.5  20.   43.75]
Row-wise means: [25.5  49.25 52.5  53.75]
Standard Deviation: 27.648462886750142
Variance: 764.4375
Minimum value: 6
Maximum value: 88
Index of minimum value: 6
Index of maximum value: 8


3D_array

In [5]:
import numpy as np

rgb_image = np.random.randint(0, 256, size=(3, 3, 3))
print(rgb_image)

red_channel = rgb_image[:, :, 0]
green_channel = rgb_image[:, :, 1]
blue_channel = rgb_image[:, :, 2]

print("Red Channel:\n", red_channel)
print("Green Channel:\n", green_channel)
print("Blue Channel:\n", blue_channel)

red_mean = np.mean(red_channel)
green_mean = np.mean(green_channel)
blue_mean = np.mean(blue_channel)

print(f"Average pixel intensity for Red channel: {red_mean}")
print(f"Average pixel intensity for Green channel: {green_mean}")
print(f"Average pixel intensity for Blue channel: {blue_mean}")

brightness_increase = 50
brightened_image = np.clip(rgb_image + brightness_increase, 0, 255)
print("Brightened Image (clipped at 255):\n", brightened_image)

[[[207  99 248]
  [ 77  51 173]
  [241 230   6]]

 [[ 75 172  79]
  [216 191   5]
  [128 129  93]]

 [[ 39  82 212]
  [147 214 239]
  [233 138  94]]]
Red Channel:
 [[207  77 241]
 [ 75 216 128]
 [ 39 147 233]]
Green Channel:
 [[ 99  51 230]
 [172 191 129]
 [ 82 214 138]]
Blue Channel:
 [[248 173   6]
 [ 79   5  93]
 [212 239  94]]
Average pixel intensity for Red channel: 151.44444444444446
Average pixel intensity for Green channel: 145.11111111111111
Average pixel intensity for Blue channel: 127.66666666666667
Brightened Image (clipped at 255):
 [[[255 149 255]
  [127 101 223]
  [255 255  56]]

 [[125 222 129]
  [255 241  55]
  [178 179 143]]

 [[ 89 132 255]
  [197 255 255]
  [255 188 144]]]
